/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package menuawal;

import cpagen.MenuCPagen;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import login.GantiPassword;
import login.LogInUI;
import logtransaksi.LogTransaksi;
import rekapdata.RekapDataPenjualanUI;
import saldo.MenuSaldo;


public class MenuAwal extends javax.swing.JFrame {

    /**
     * Creates new form MenuAwal
     */
    private LogTransaksi log;
    private MenuSaldo saldo;
    private RekapDataPenjualanUI rekap;
    private MenuCPagen cp;
    private GantiPassword ganti;
    
    public MenuAwal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LogTransaksi = new javax.swing.JButton();
        StokPulsa = new javax.swing.JButton();
        RekapData = new javax.swing.JButton();
        CPagen = new javax.swing.JButton();
        GantiPassword = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LogTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogTransaksi.setText("LogTransaksi");
        LogTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogTransaksiActionPerformed(evt);
            }
        });

        StokPulsa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StokPulsa.setText("StokPulsa");
        StokPulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StokPulsaActionPerformed(evt);
            }
        });

        RekapData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RekapData.setText("RekapData");
        RekapData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RekapDataActionPerformed(evt);
            }
        });

        CPagen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CPagen.setText("Contact Person Agen");
        CPagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPagenActionPerformed(evt);
            }
        });

        GantiPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GantiPassword.setText("Ganti Password");
        GantiPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GantiPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CPagen, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(GantiPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RekapData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StokPulsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LogTransaksi)
                .addGap(18, 18, 18)
                .addComponent(StokPulsa)
                .addGap(18, 18, 18)
                .addComponent(RekapData)
                .addGap(18, 18, 18)
                .addComponent(CPagen)
                .addGap(18, 18, 18)
                .addComponent(GantiPassword)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogTransaksiActionPerformed
        log = new LogTransaksi();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogTransaksiActionPerformed

    private void CPagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPagenActionPerformed
        cp = new MenuCPagen();
        cp.setVisible(true);
        dispose();
    }//GEN-LAST:event_CPagenActionPerformed

    private void StokPulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StokPulsaActionPerformed
        saldo = new MenuSaldo();
        saldo.setVisible(true);
        dispose();
    }//GEN-LAST:event_StokPulsaActionPerformed

    private void RekapDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RekapDataActionPerformed
        rekap = new RekapDataPenjualanUI();
        rekap.setVisible(true);
        dispose();
    }//GEN-LAST:event_RekapDataActionPerformed

    private void GantiPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GantiPasswordActionPerformed
        ganti = new GantiPassword();
        ganti.setVisible(true);
        dispose();
    }//GEN-LAST:event_GantiPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CPagen;
    private javax.swing.JButton GantiPassword;
    private javax.swing.JButton LogTransaksi;
    private javax.swing.JButton RekapData;
    private javax.swing.JButton StokPulsa;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void close() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}